export interface Charity {
  id: string;
  name: string;
  logo: string;
  description: string;
  category: string;
  location: string;
  rating: number;
  yearFounded: number;
  size: "small" | "medium" | "large";
  verified: boolean;
  urgentNeed: boolean;
  taxDeductible: boolean;
  impactMetric: string;
  donationTotal: number;
  donorsCount: number;
  regions: string[];
}

export const MockCharities: Charity[] = [
  {
    id: "1",
    name: "Global Education Fund",
    logo: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?q=80&w=1450&auto=format&fit=crop",
    description: "Providing educational opportunities for children in underserved communities around the world. We build schools, train teachers, and provide learning materials.",
    category: "education",
    location: "Global",
    rating: 4.8,
    yearFounded: 2005,
    size: "large",
    verified: true,
    urgentNeed: false,
    taxDeductible: true,
    impactMetric: "2.5M children reached",
    donationTotal: 12500000,
    donorsCount: 45000,
    regions: ["africa", "asia", "south-america"]
  },
  {
    id: "2",
    name: "Clean Water Initiative",
    logo: "https://images.unsplash.com/photo-1624811072506-2cd4fe47774b?q=80&w=1450&auto=format&fit=crop",
    description: "Providing clean water solutions to communities in need around the world. Our projects have helped over 5 million people gain access to clean drinking water.",
    category: "health",
    location: "Africa, Asia",
    rating: 4.9,
    yearFounded: 1998,
    size: "large",
    verified: true,
    urgentNeed: true,
    taxDeductible: true,
    impactMetric: "5M+ people served",
    donationTotal: 18700000,
    donorsCount: 62000,
    regions: ["africa", "asia"]
  },
  {
    id: "3",
    name: "Rainforest Alliance",
    logo: "https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?q=80&w=1450&auto=format&fit=crop",
    description: "Working to protect and preserve forests and natural habitats. Our efforts have saved millions of acres of critical ecosystems.",
    category: "environment",
    location: "South America",
    rating: 4.7,
    yearFounded: 2001,
    size: "medium",
    verified: true,
    urgentNeed: true,
    taxDeductible: true,
    impactMetric: "3M acres preserved",
    donationTotal: 8900000,
    donorsCount: 29000,
    regions: ["south-america"]
  },
  {
    id: "4",
    name: "Hunger Relief Network",
    logo: "https://images.unsplash.com/photo-1615397587950-3651b2d0f477?q=80&w=1450&auto=format&fit=crop",
    description: "Fighting hunger by providing meals to those in need and addressing the root causes of food insecurity.",
    category: "poverty",
    location: "North America",
    rating: 4.5,
    yearFounded: 1995,
    size: "large",
    verified: true,
    urgentNeed: false,
    taxDeductible: true,
    impactMetric: "12M meals served annually",
    donationTotal: 14200000,
    donorsCount: 51000,
    regions: ["north-america"]
  },
  {
    id: "5",
    name: "Global Health Partners",
    logo: "https://images.unsplash.com/photo-1532938911079-1b06ac7ceec7?q=80&w=1450&auto=format&fit=crop",
    description: "Providing medical care, supplies, and training to healthcare workers in developing countries.",
    category: "health",
    location: "Global",
    rating: 4.6,
    yearFounded: 2007,
    size: "medium",
    verified: true,
    urgentNeed: false,
    taxDeductible: true,
    impactMetric: "1.2M patients treated",
    donationTotal: 7600000,
    donorsCount: 18000,
    regions: ["africa", "asia", "south-america"]
  },
  {
    id: "6",
    name: "Animal Rescue Foundation",
    logo: "https://images.unsplash.com/photo-1548681528-6a5c45b66b42?q=80&w=1450&auto=format&fit=crop",
    description: "Rescuing and rehabilitating abandoned and abused animals, and finding them forever homes.",
    category: "animals",
    location: "North America, Europe",
    rating: 4.4,
    yearFounded: 2003,
    size: "medium",
    verified: true,
    urgentNeed: false,
    taxDeductible: true,
    impactMetric: "75,000 animals rescued",
    donationTotal: 5100000,
    donorsCount: 42000,
    regions: ["north-america", "europe"]
  },
  {
    id: "7",
    name: "Emergency Disaster Response",
    logo: "https://images.unsplash.com/photo-1587654780291-39c9404d746b?q=80&w=1450&auto=format&fit=crop",
    description: "Providing immediate relief and long-term support to communities affected by natural disasters.",
    category: "disaster",
    location: "Global",
    rating: 4.9,
    yearFounded: 1999,
    size: "large",
    verified: true,
    urgentNeed: true,
    taxDeductible: true,
    impactMetric: "250+ disaster responses",
    donationTotal: 22300000,
    donorsCount: 78000,
    regions: ["global"]
  },
  {
    id: "8",
    name: "Children First Alliance",
    logo: "https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?q=80&w=1450&auto=format&fit=crop",
    description: "Advocating for children's rights and providing protection, education, and healthcare to vulnerable children.",
    category: "human-rights",
    location: "Global",
    rating: 4.7,
    yearFounded: 2002,
    size: "medium",
    verified: true,
    urgentNeed: false,
    taxDeductible: true,
    impactMetric: "850,000 children served",
    donationTotal: 11200000,
    donorsCount: 37000,
    regions: ["global"]
  },
  {
    id: "9",
    name: "Cultural Heritage Trust",
    logo: "https://images.unsplash.com/photo-1551913902-c92207136625?q=80&w=1450&auto=format&fit=crop",
    description: "Preserving cultural heritage sites and traditions around the world for future generations.",
    category: "art-culture",
    location: "Global",
    rating: 4.3,
    yearFounded: 2010,
    size: "small",
    verified: true,
    urgentNeed: false,
    taxDeductible: true,
    impactMetric: "215 sites preserved",
    donationTotal: 3500000,
    donorsCount: 12000,
    regions: ["global"]
  },
  {
    id: "10",
    name: "Refugee Support Network",
    logo: "https://images.unsplash.com/photo-1606787364406-a3cdf06c6d0c?q=80&w=1450&auto=format&fit=crop",
    description: "Providing shelter, legal assistance, and integration support for refugees and displaced persons.",
    category: "humanitarian",
    location: "Europe, Middle East",
    rating: 4.8,
    yearFounded: 2015,
    size: "medium",
    verified: true,
    urgentNeed: true,
    taxDeductible: true,
    impactMetric: "120,000 refugees assisted",
    donationTotal: 9800000,
    donorsCount: 34000,
    regions: ["europe", "asia"]
  },
  {
    id: "11",
    name: "Ocean Conservation Group",
    logo: "https://images.unsplash.com/photo-1518020382113-a7e8fc38eac9?q=80&w=1450&auto=format&fit=crop",
    description: "Working to protect marine ecosystems, reduce plastic pollution, and promote sustainable fishing practices.",
    category: "environment",
    location: "Global",
    rating: 4.5,
    yearFounded: 2008,
    size: "medium",
    verified: true,
    urgentNeed: false,
    taxDeductible: true,
    impactMetric: "500,000 lbs of waste removed",
    donationTotal: 6700000,
    donorsCount: 28000,
    regions: ["global"]
  },
  {
    id: "12",
    name: "Women's Empowerment Coalition",
    logo: "https://images.unsplash.com/photo-1573497161664-fd4ff3486e26?q=80&w=1450&auto=format&fit=crop",
    description: "Promoting gender equality and empowering women through education, entrepreneurship, and advocacy.",
    category: "human-rights",
    location: "Global",
    rating: 4.6,
    yearFounded: 2012,
    size: "medium",
    verified: true,
    urgentNeed: false,
    taxDeductible: true,
    impactMetric: "350,000 women empowered",
    donationTotal: 7200000,
    donorsCount: 31000,
    regions: ["global"]
  },
  {
    id: "13",
    name: "Affordable Housing Initiative",
    logo: "https://images.unsplash.com/photo-1460317442991-0ec209397118?q=80&w=1450&auto=format&fit=crop",
    description: "Building and renovating homes for low-income families and advocating for affordable housing policies.",
    category: "poverty",
    location: "North America",
    rating: 4.7,
    yearFounded: 1997,
    size: "medium",
    verified: true,
    urgentNeed: false,
    taxDeductible: true,
    impactMetric: "15,000 homes built",
    donationTotal: 10500000,
    donorsCount: 42000,
    regions: ["north-america"]
  },
  {
    id: "14",
    name: "Digital Education Access",
    logo: "https://images.unsplash.com/photo-1584697964400-2af6a2f6204c?q=80&w=1450&auto=format&fit=crop",
    description: "Bridging the digital divide by providing technology and internet access to underserved communities.",
    category: "education",
    location: "Global",
    rating: 4.4,
    yearFounded: 2016,
    size: "small",
    verified: true,
    urgentNeed: false,
    taxDeductible: true,
    impactMetric: "250,000 devices distributed",
    donationTotal: 4800000,
    donorsCount: 19000,
    regions: ["global"]
  },
  {
    id: "15",
    name: "Mental Health Alliance",
    logo: "https://images.unsplash.com/photo-1527137342181-19aab11a8ee8?q=80&w=1450&auto=format&fit=crop",
    description: "Providing mental health services, resources, and advocacy to reduce stigma and increase access to care.",
    category: "health",
    location: "Global",
    rating: 4.5,
    yearFounded: 2014,
    size: "small",
    verified: true,
    urgentNeed: false,
    taxDeductible: true,
    impactMetric: "1M+ people supported",
    donationTotal: 5600000,
    donorsCount: 23000,
    regions: ["global"]
  },
  {
    id: "16",
    name: "Clean Energy Foundation",
    logo: "https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?q=80&w=1450&auto=format&fit=crop",
    description: "Accelerating the transition to clean energy through technology innovation, policy advocacy, and community projects.",
    category: "environment",
    location: "Global",
    rating: 4.2,
    yearFounded: 2011,
    size: "medium",
    verified: true,
    urgentNeed: false,
    taxDeductible: true,
    impactMetric: "500+ projects completed",
    donationTotal: 8100000,
    donorsCount: 27000,
    regions: ["global"]
  },
  {
    id: "17",
    name: "Youth Leadership Academy",
    logo: "https://images.unsplash.com/photo-1511632765486-a01980e01a18?q=80&w=1450&auto=format&fit=crop",
    description: "Developing future leaders through education, mentorship, and community service opportunities for young people.",
    category: "education",
    location: "North America, Europe",
    rating: 4.6,
    yearFounded: 2009,
    size: "small",
    verified: true,
    urgentNeed: false,
    taxDeductible: true,
    impactMetric: "50,000 youth trained",
    donationTotal: 4200000,
    donorsCount: 18000,
    regions: ["north-america", "europe"]
  },
  {
    id: "18",
    name: "Food Security Initiative",
    logo: "https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?q=80&w=1450&auto=format&fit=crop",
    description: "Developing sustainable food systems and agricultural practices to ensure long-term food security.",
    category: "poverty",
    location: "Africa, Asia",
    rating: 4.7,
    yearFounded: 2004,
    size: "medium",
    verified: true,
    urgentNeed: true,
    taxDeductible: true,
    impactMetric: "2M people reached",
    donationTotal: 9300000,
    donorsCount: 32000,
    regions: ["africa", "asia"]
  }
];
